/**
 * Sidebar configuration for Jatrix documentation.
 */
// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Use the sidebar generated by docusaurus-plugin-openapi-docs
// eslint-disable-next-line @typescript-eslint/no-require-imports
const apiSidebar = require("./docs/api/sidebar").default;

const sidebars: SidebarsConfig = {
  docs: [
    { type: "doc", id: "intro" },
    { type: "doc", id: "spec", label: "Vision and Principles" },
    {
      type: "category",
      label: "Jatrix API",
      link: {
        type: "generated-index",
        title: "Jatrix API Reference",
        description:
          "REST API for identity, multi-tenancy, authorization, and product governance.",
        slug: "api",
      },
      items: apiSidebar,
    },
  ],
};

export default sidebars;
